# Generated by Django 6.0.6 on 2026-07-09 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(help_text='Amazon Seller/Merchant ID', max_length=100, unique=True)),
                ('timezone', models.CharField(choices=[('eastern', 'Eastern (EST)'), ('central', 'Central (CST)'), ('mountain', 'Mountain (MST)'), ('pacific', 'Pacific (PST)'), ('gmt', 'GMT')], default='gmt', max_length=30, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('commision_rate', models.DecimalField(decimal_places=1, default=20.0, max_digits=12)),
                ('amazon_joined_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'db_table': 'sellers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seller.order')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('product', 'Sponsored Products'), ('brand', 'Sponsored Brands'), ('display', 'Sponsored Displays')], default='product', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amazon_campaign_id', models.CharField(blank=True, null=True)),
                ('target_acos', models.PositiveIntegerField()),
                ('ppc_spend', models.IntegerField(default=0)),
                ('ppc_sales', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('bid', models.DecimalField(decimal_places=2, default=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='seller.seller')),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ['-created_at'],
            },
        ),
    ]
