# Generated by Django 6.0.6 on 2026-07-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['-created_at'], 'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AlterModelTable(
            name='seller',
            table='sellers',
        ),
    ]
