# Generated by Django 6.0.6 on 2026-07-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_options_alter_seller_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='amazon_joined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
