# Generated by Django 6.0.6 on 2026-07-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ads_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fba_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_ad_order',
            field=models.BooleanField(default=False),
        ),
    ]
