# Generated by Django 6.0.6 on 2026-07-02 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_amazon_joined_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_available', models.IntegerField(default=0)),
                ('inventory_reserved', models.IntegerField(default=0)),
                ('inventory_inbound', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ad_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ad_clicks', models.IntegerField(default=0)),
                ('ad_orders', models.IntegerField(default=0)),
                ('acos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('roas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amazon_referral_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fba_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('storage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advertising_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suppressed', 'Suppressed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller')),
            ],
        ),
    ]
