# Generated by Django 6.0.6 on 2026-07-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_orderitem_ads_cost_orderitem_fba_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_id',
        ),
    ]
