# Generated by Django 6.0.6 on 2026-07-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='products/'),
        ),
    ]
