# Generated by Django 6.0.6 on 2026-07-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gross_revenue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
