# Generated by Django 6.0.6 on 2026-07-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_product_gross_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
