# Generated by Django 6.0.6 on 2026-07-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_alter_product_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_profit',
            field=models.IntegerField(default=0),
        ),
    ]
