# Generated by Django 6.0.6 on 2026-07-03 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_alter_product_net_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(db_index=True, max_length=30)),
                ('marketplace', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('amazon_order_id', models.CharField(max_length=30, unique=True)),
                ('purchase_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=30)),
                ('fulfillment_channel', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_country', models.CharField(blank=True, max_length=5, null=True)),
                ('number_of_items', models.PositiveIntegerField(default=0)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['seller_id'], name='orders_seller__57aebd_idx'), models.Index(fields=['marketplace'], name='orders_marketp_83eb7e_idx'), models.Index(fields=['purchase_date'], name='orders_purchas_632de5_idx'), models.Index(fields=['order_status'], name='orders_order_s_0d3802_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(db_index=True, max_length=30)),
                ('marketplace', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('order_item_id', models.CharField(max_length=30, unique=True)),
                ('asin', models.CharField(db_index=True, max_length=20)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('quantity_ordered', models.PositiveIntegerField(default=1)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promotion_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_status', models.CharField(max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seller.order')),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['asin'], name='order_items_asin_e8d78e_idx'), models.Index(fields=['sku'], name='order_items_sku_1b9f90_idx'), models.Index(fields=['seller_id'], name='order_items_seller__0dab98_idx'), models.Index(fields=['item_status'], name='order_items_item_st_1f19ad_idx')],
            },
        ),
    ]
