# Generated by Django 6.0.6 on 2026-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_remove_order_seller_id_order_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
