# Generated by Django 6.0.6 on 2026-07-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='fee_ratio',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=12),
        ),
    ]
