# Generated by Django 6.0.6 on 2026-07-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_seller_fee_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='fee_ratio',
            new_name='commision_rate',
        ),
    ]
