# Generated by Django 6.0.6 on 2026-07-03 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_rename_fee_ratio_seller_commision_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('product', 'Sponsored Products'), ('brand', 'Sponsored Brands'), ('display', 'Sponsored Displays')], default='product', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('budget', models.PositiveIntegerField()),
                ('amazon_campaign_id', models.CharField(blank=True, null=True)),
                ('target_acos', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='seller.seller')),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ['-created_at'],
            },
        ),
    ]
