# Generated by Django 6.0.6 on 2026-07-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ppc_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ppc_spend',
            field=models.IntegerField(default=0),
        ),
    ]
