# Generated by Django 6.0.6 on 2026-07-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_campaign_clicks_campaign_ppc_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
        ),
    ]
