# Generated by Django 6.0.6 on 2026-07-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_campaign_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
