# Generated by Django 6.0.6 on 2026-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_alter_campaign_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ctr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
