# Generated by Django 6.0.6 on 2026-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_campaign_ctr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='timezone',
            field=models.CharField(choices=[('eastern', 'Eastern (EST)'), ('central', 'Central (CST)'), ('mountain', 'Mountain (MST)'), ('pacific', 'Pacific (PST)'), ('gmt', 'GMT')], default='gmt', max_length=30, null=True),
        ),
    ]
