# Generated by Django 6.0.6 on 2026-07-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_campaign_ctr'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='vendor',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='seller.seller'),
            preserve_default=False,
        ),
    ]
