# Generated by Django 6.0.6 on 2026-07-09 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('account', 'Account'), ('data_import', 'Data Import'), ('report', 'Report')], max_length=30)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('csv_upload', 'CSV Upload'), ('csv_download', 'CSV Download'), ('report_download', 'Report Download'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
